version: "3"
services:
  based-AIO-image:
    container_name: based-bot
    image: python:3.12
    working_dir: /code
    environment:
      - TOKEN=<none>
      - HTTP_PROXY=http://sky38.synology.me:49185
      - HTTPS_PROXY=http://sky38.synology.me:49185
      - NO_PROXY=localhost,127.0.0.1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G
    volumes:
      - .:/code
    command: ["python", "-m", "main", "--host", "0.0.0.0", "--reload"]
    entrypoint: >
      sh -c "apt-get update && apt-get install -y ffmpeg && pip install --no-cache-dir -r /code/requirements.txt && exec \"$$0\" \"$$@\""
    build:
      context: .
      args:
        HTTP_PROXY: http://sky38.synology.me:49185
        HTTPS_PROXY: http://sky38.synology.me:49185
        NO_PROXY: localhost,127.0.0.1
    stdin_open: true
    tty: true
