version: "3"
services:
  based-AIO-image:
    container_name: based-bot
    image: python:3.12
    working_dir: /code
    environment:
      - TOKEN=<not needed as of now>
      - YT_LOGIN=<add your youtube E-Mail Here>
      - YT_PASSWORD=<add your password here>
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 1G

    volumes:
      - .:/code
    command: ["python", "-m", "main", "--host", "0.0.0.0", "--reload"]
    entrypoint: >
      sh -c "apt-get update && apt-get install -y ffmpeg && pip install --no-cache-dir -r /code/requirements.txt && exec \"$$0\" \"$$@\""

    # WIP below, this is needed to complete the setup on a fresh bot
    stdin_open: true   # Keep STDIN open even if not attached | Disable after initial setup
    tty: true          # Allocate a pseudo-TTY | Disable after initial setup